
name: CI/CD Pipeline

on:
  # Trigger on push to main branch
  push:
    branches: [ main ]
  
  # Trigger pull requests to main branch
  pull_request:
    branches: [ main ]
  
  # Schedule weekly run on Sunday
  schedule:
    - cron: '0 0 * * 0'  # Runs at midnight every Sunday

# Environment variables can be set here if needed
env:
  DOCKER_REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }} | toLower


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    # Checkout repository code
    - name: Checkout Repository
      uses: actions/checkout@v4

    # Setup Docker BuildX for better build performance
    - name: Set up Docker BuildX
      uses: docker/setup-buildx-action@v3

    # Login to GitHub Container Registry
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Build and push Docker image
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ env.DOCKER_REGISTRY }}/tharangasg/solar-generation-prediction:latest
          ${{ env.DOCKER_REGISTRY }}/tharangasg/solar-generation-prediction:${{ github.sha }}