# name: Deploy to Azure Container Instance

# on:
#   push:
#     branches:
#       - main
#   schedule:
#     - cron: '0 0 * * 0'  # Runs every Sunday at midnight (UTC)

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3

#       - name: Log in to Azure
#         uses: azure/login@v1
#         with:
#           creds: ${{ secrets.AZURE_CREDENTIALS }}

#       - name: Log in to Azure Container Registry (ACR)
#         run: |
#           az acr login --name ${{ secrets.ACR_NAME }}

#       - name: Build and push Docker image
#         run: |
#           docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/solar-gen-pred:latest .
#           docker push ${{ secrets.ACR_NAME }}.azurecr.io/solar-gen-pred:latest

#       - name: Deploy to Azure Container Instance (ACI)
#         run: |
#           az container create \
#             --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
#             --name solar-gen-pred-container \
#             --image ${{ secrets.ACR_NAME }}.azurecr.io/solar-gen-pred:latest \
#             --dns-name-label solar-gen-pred-app \
#             --ports 5000

# name: CI/CD Pipeline

# on:
#   # Trigger on push to main branch
#   push:
#     branches: [ main ]
  
#   # Trigger pull requests to main branch
#   pull_request:
#     branches: [ main ]
  
#   # Schedule weekly run on Sunday
#   schedule:
#     - cron: '0 0 * * 0'  # Runs at midnight every Sunday

# # Environment variables can be set here if needed
# env:
#   DOCKER_REGISTRY: ghcr.io
#   IMAGE_NAME: ${{ github.repository }}

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: read
#       packages: write

#     steps:
#     # Checkout repository code
#     - name: Checkout Repository
#       uses: actions/checkout@v4

#     # Setup Docker BuildX for better build performance
#     - name: Set up Docker BuildX
#       uses: docker/setup-buildx-action@v3

#     # Login to GitHub Container Registry
#     - name: Login to GitHub Container Registry
#       uses: docker/login-action@v3
#       with:
#         registry: ghcr.io
#         username: ${{ github.actor }}
#         password: ${{ secrets.GITHUB_TOKEN }}

#     # Build and push Docker image
#     - name: Build and Push Docker Image
#       uses: docker/build-push-action@v5
#       with:
#         context: .
#         push: true
#         tags: |
#           ghcr.io/${{ github.repository }}:latest
#           ghcr.io/${{ github.repository }}:${{ github.sha }}

#     # Optional: Deploy to your target environment
#     - name: Deploy to Azure
#       env:
#         # Use GitHub secrets for sensitive information
#         AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
#         HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
#       run: |
#         # Add your deployment script here
#         # Example Azure deployment commands
#         az login --service-principal -u ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }} -p ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }} --tenant ${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}
#         # Add specific deployment commands for your project

#     # Optional: Run tests
#     - name: Run Tests
#       run: |
#         # Add your test commands here
#         docker run --rm ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest pytest tests/



name: CI/CD Pipeline

on:
  # Trigger on push to main branch
  push:
    branches: [ main ]
  
  # Trigger pull requests to main branch
  pull_request:
    branches: [ main ]
  
  # Schedule weekly run on Sunday
  schedule:
    - cron: '0 0 * * 0'  # Runs at midnight every Sunday

# Environment variables can be set here if needed
env:
  DOCKER_REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    # Checkout repository code
    - name: Checkout Repository
      uses: actions/checkout@v4

    # Setup Docker BuildX for better build performance
    - name: Set up Docker BuildX
      uses: docker/setup-buildx-action@v3

    # Login to GitHub Container Registry
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Build and push Docker image
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ghcr.io/${{ github.repository }}:latest
          ghcr.io/${{ github.repository }}:${{ github.sha }}