# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - solargenwebapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://solargenwebacr.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_b563b0ec4cc44f9096a932f01dfd9332 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_908eb24d7fe54892ab0352dee78299ed }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: solargenwebacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_b563b0ec4cc44f9096a932f01dfd9332 }}/solargenweb:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'solargenwebapp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_2bbeddc2c00e418ea2b051f8aecfbb09 }}
        images: 'solargenwebacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_b563b0ec4cc44f9096a932f01dfd9332 }}/solargenweb:${{ github.sha }}'