# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - solargenpred

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://solargenwebacr.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_1848bfd8f08f4f5c94c85d73f970ff75 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_477ffcbd235749768e1c8b4d776660a1 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: solargenwebacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_1848bfd8f08f4f5c94c85d73f970ff75 }}/solargenweb:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'solargenpred'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_335f6ace6c8f40889e3b3d99743a1e39 }}
        images: 'solargenwebacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_1848bfd8f08f4f5c94c85d73f970ff75 }}/solargenweb:${{ github.sha }}'